hmrc/view-external-guidance-frontend

README.md
Update of README file to test GitHub integration with Jenkins and Slack.
=> Update README file to test GitHub Integration

app/models/ocelot/stanzas/CalloutType.scala, test/models/ocelot/stanzas/CalloutStanzaSpec.scala
=> Eg 229 - Update of CalloutStanza tests

app/views/components/h1_heading.scala.html, app/views/components/h2_heading.scala.html, app/views/components/h3_heading.scala.html, test/base/ViewSpec.scala, test/views/components/H1HeadingSpec.scala, test/views/components/H2HeadingSpec.scala, test/views/components/H3HeadingSpec.scala
UI Heading components and tests.
=> EG-279 Heading

app/services/GuidanceService.scala, app/services/PageBuilder.scala, app/services/UIBuilder.scala, test/models/ocelot/PrototypeJsonSpec.scala, test/services/GuidanceServiceSpec.scala, test/services/PageBuilderSpec.scala, test/services/UIBuilderSpec.scala
Convert PageBuilder and UIBuilder objects into classes that can be injected into other classes where necessary.
=> EG-338 Convert PageBuilder and UIBuilder

app/connectors/httpParsers/GetProcessHttpParser.scala, project/AppDependencies.scala, project/plugins.sbt, test/connectors/httpParsers/GetProcessHttpParserSpec.scala, test/connectors/httpParsers/HttpParserSpec.scala, test/controllers/SwitchLanguageControllerSpec.scala
scalatest not upgrade to latest as encoutered bug described here https://github.com/sbt/sbt/issues/5308 . Although reported against sbt, it does not occur when using current version of scalatest
=> EG-696, upgraded sbt, plugins and dependencies

app/views/components/error_summary.scala.html, conf/messages.cy, conf/messages.en
for the error page and accessibility statement link
=> EG-717 - Address accessibility audit findings 

conf/application.conf
Once merged need to ensure GA still works
=> Updating Content Security Policy to tie things down more

conf/application.conf
ensuring additional restrictions for PEN Test still allow GTM to work correctly
=> updating CSP to ensure GTM / GA works

app/controllers/SessionTimeoutPageController.scala, app/views/delete_your_answers.scala.html, conf/messages.cy, conf/messages.en, test/controllers/SessionTimeoutPageControllerSpec.scala, test/views/components/SessionTimeoutSpec.scala
and updates to simplify page layouts for timeout/delete your answers
=> Change to text after Louise Review

app/views/main_layout.scala.html, conf/messages.cy
Added language setting to the timeout dialogue and changed welsh text after review by welsh language area
=> changes for welsh timeout

app/models/ui/Input.scala, app/views/input_page.scala.html
In actuality only the button was updated.
=> EG-998 Experiment using Gov UK and HMRC frontend components for button and currency input

app/views/components/input.scala.html, app/views/components/input_field.scala.html
Merged in changes on top of master
=> EG-1046 - Accessibility

app/services/UIBuilder.scala, test/services/UIBuilderSpec.scala
Journey tests EG-1086, needed to be merged before this branch
=> EG-1085, Callouts of type Important ignored

app/models/ocelot/stanzas/CalloutStanza.scala, app/models/ocelot/stanzas/CalloutType.scala, app/models/ocelot/stanzas/NoteGroup.scala, app/models/ui/InsetText.scala, app/services/Aggregator.scala, app/services/UIBuilder.scala, app/views/components/inset_text.scala.html, app/views/components/render_components.scala.html, test/models/ocelot/stanzas/CalloutStanzaSpec.scala, test/services/AggregatorSpec.scala, test/services/UIBuilderSpec.scala, test/views/components/InsetTextSpec.scala, test/views/components/PageSpec.scala
includes all sub tasks on ticket EG-1070 (other than testing)
also removing some warnings from test classes
=> EG-1113 adding inset text components

app/models/ocelot/stanzas/YourCallGroup.scala, app/services/Aggregator.scala, app/services/UIBuilder.scala, test/models/ocelot/stanzas/InputStanzaSpec.scala
bringing yourcall in line with other grouped components
=> EG-1119 - YourCall Stacking

app/views/components/input.scala.html, app/views/components/input_field.scala.html, app/views/main_layout.scala.html, test/views/components/InputSpec.scala, test/views/components/PageSpec.scala
remove fieldset on input page
remove 2nd question
associate error with input
=> Fixing accessibility issues:

app/controllers/GuidanceController.scala, app/models/ocelot/stanzas/InputStanza.scala, app/models/ui/Input.scala, app/models/ui/Page.scala, app/services/PageBuilder.scala, app/services/UIBuilder.scala, app/views/components/h1_heading_with_fieldset.scala.html, app/views/components/h1_heading_with_label.scala.html, app/views/components/input_date.scala.html, app/views/components/input_date_field.scala.html, app/views/input_date_page.scala.html, conf/messages.cy, conf/messages.en, project/AppDependencies.scala, project/plugins.sbt, test/controllers/GuidanceControllerSpec.scala, test/models/ocelot/stanzas/CalloutStanzaSpec.scala, test/models/ocelot/stanzas/InputStanzaSpec.scala, test/services/AggregatorSpec.scala, test/services/PageBuilderSpec.scala, test/services/UIBuilderSpec.scala, test/utils/StanzaHelper.scala, test/views/components/H1HeadingWithFieldsetSpec.scala, test/views/components/H1HeadingWithLabelSpec.scala, test/views/components/InputSpec.scala
Merged in current master changes
=> EG-1134 date input

app/models/ocelot/stanzas/InputStanza.scala, app/models/ui/Input.scala, app/models/ui/OutputFormat.scala, app/models/ui/UIComponent.scala, app/services/TextBuilder.scala, app/services/UIBuilder.scala, app/views/components/input_currency_field.scala.html, app/views/components/input_field.scala.html, app/views/components/input_number_field.scala.html, test/models/ocelot/stanzas/InputStanzaSpec.scala, test/services/PageBuilderSpec.scala, test/utils/StanzaHelper.scala, test/views/components/InputSpec.scala, test/views/components/RenderTextSpec.scala, test/views/components/TableSpec.scala
Use with external-guidance branch EG-1207-Number-Input from
=> EG-1208 number input

app/core/models/ocelot/LabelCache.scala, app/forms/FormsHelper.scala, app/models/ui/FormComponent.scala, app/models/ui/Page.scala, app/models/ui/Sequence.scala, app/services/UIBuilder.scala, app/views/components/sequence.scala.html, app/views/components/sequence_checkbox.scala.html, app/views/components/sequence_checkboxes.scala.html, test/base/BaseSpec.scala, test/core/models/StanzaHelper.scala, test/core/models/ocelot/LabelSpec.scala, test/core/models/ocelot/ProcessSpec.scala, test/core/services/PageBuilderSpec.scala, test/services/EnglishUIBuilderSpec.scala, test/services/WelshUIBuilderSpec.scala, test/views/components/PageSpec.scala, test/views/components/SequenceSpec.scala
Note, I've used the SubmittedTextAnswerFormProvider for the time being; this may change. I have also used the identifier name[index] for the check box identifiers. I think this will work with the "list" type binding, but I'll find out more later.
=> EG-1296 Implement Sequence UI component and render view

app/views/components/answers.scala.html, app/views/components/error_message.scala.html, app/views/components/input.scala.html, app/views/components/input_date.scala.html, app/views/components/question.scala.html, app/views/components/sequence.scala.html, app/views/components/summary_row.scala.html, test/views/components/ErrorSpec.scala, test/views/components/InputSpec.scala, test/views/components/QuestionSpec.scala, test/views/components/SequenceSpec.scala
Updated Html in line with govuk-frontend version 4.0.0 release notes. Additional journey test PR that needs merging [here](https://github.com/hmrc/view-external-guidance-journey-tests/pull/112)
=> DL-7243: implemented recommeneded changes from GOVUK-FE v4 release notes

project/AppDependencies.scala
Update play-frontend-hmrc to latest version
Unit, it and ATs all pass OK
=> DL-9504 update play frontend hmtc to latest

app/views/admin/process_map.scala.html, app/views/main_layout.scala.html, app/views/session_blocked.scala.html
=> DL-9815-fix2, corrected position of language switch on the cookies blocked warning page

conf/application.conf
Not used as removing DATASTREAM dependency from EG_ALL profile
=> DL-12512 remove auditing locally

app/controllers/GuidanceController.scala, app/repositories/SessionRepository.scala, app/services/GuidanceService.scala, app/services/SessionService.scala, test/controllers/GuidanceControllerSpec.scala, test/mocks/MockGuidanceService.scala, test/mocks/MockSessionRespository.scala, test/mocks/MockSessionService.scala, test/services/GuidanceServiceSpec.scala, test/services/SessionServiceSpec.scala
**Remark.** Journey Tests for this branch fail for usage of PassPhrases - this will be addressed separately.
=> Dl 14453, Update SessionRepository to include persistence of List[LabelOperation]

build.sbt, project/AppDependencies.scala, project/plugins.sbt
=> DL-14995, dependencyUpdates
